#!/bin/bash

set -e

if [ "$#" == "0" ]; then
    echo "Expected: [project name] [version]"
    exit 1
fi

PROJECT_NAME=$1
VERSION=$2
if [ -z "$VERSION" ]; then
    VERSION="1.0.0"
fi

echo Building $PROJECT_NAME - $VERSION

TARGET=target
TARGET_VIRTUAL_ENV=/opt/deployment/$PROJECT_NAME/virtualenv

rm -rf $TARGET
rm -rf $TARGET_VIRTUAL_ENV
mkdir -p $TARGET_VIRTUAL_ENV
virtualenv --no-site-packages --distribute $TARGET_VIRTUAL_ENV
source $TARGET_VIRTUAL_ENV/bin/activate

# use the cache unless you like redownloading things
pip install --download-cache /tmp/pip_cache -r requirements.txt
deactivate

mkdir -p $TARGET/opt/deployment/$PROJECT_NAME
mv $TARGET_VIRTUAL_ENV $TARGET/opt/deployment/

# copy over root folder mirror, anything you needed
cp -r ./deb/* $TARGET/

# copy project files here
mkdir $TARGET/opt/$PROJECT_NAME

# TODO generalize this to a dependency list file
fpm -s dir -t deb -n "$PROJECT_NAME" -v "$VERSION" \
--prefix / \
-d "build-essential" \
-d "git" \
-d "python" \
-d "python-pip" \
-d "python-dev" \
-d "libxml2-dev" \
-d "libxslt1-dev" \
-d "curl" \
-d "libcurl4-gnutls-dev" \
-d "libmysqlclient-dev" \
-d "monit" \
-d "nginx" \
--directories "/opt/$PROJECT_NAME" \
--after-install after_install.sh \
--before-remove before_remove.sh \
-C $TARGET .
